# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('book_type', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('edition', models.IntegerField()),
                ('no_of_books', models.IntegerField()),
            ],
        ),
    ]
