# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='edition',
            new_name='Edition',
        ),
    ]
