# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170220_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Edition',
            new_name='edition',
        ),
    ]
