# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_usertable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTable',
            new_name='User',
        ),
    ]
