# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn_no',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
