# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20170316_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('MCA', 'MCA')], max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th')], max_length=3),
        ),
    ]
