# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20170317_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Computer', 'Computer'), ('Math', 'Math'), ('Economics', 'Economics'), ('Accounting', 'Accounting'), ('Others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
